---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.btsync.repo }} precise main'
        key_url: '{{ apt_repos.btsync.key_url }}'
  - role: monitoring-common
  - role: logging-config
    service: glance
    logdata: "{{ glance.logs }}"
  - role: openstack-source
    project_name: glance
    project_rev: "{{ glance.source.rev }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: glance
    package_alternatives: "{{ glance.package.console_scripts }}"
    when: openstack_install_method == 'package'
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
